---
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y unzip qemu-kvm qemu-utils qemu-block-extra

install:
  - wget https://releases.hashicorp.com/packer/1.6.2/packer_1.6.2_linux_amd64.zip -O packer.zip
  - unzip packer.zip
  - sudo mv packer /usr/bin/packer
  - rm packer.zip
  - cd "$TRAVIS_BUILD_DIR"

script:
  - travis_wait 45 sudo /usr/bin/packer build -var 'boot_wait=1m' alpine-template.json
